"""empty message

Revision ID: 707d364d278e
Revises: 101a83d34ec4
Create Date: 2020-07-22 21:15:05.789671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707d364d278e'
down_revision = '101a83d34ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trails_route', table_name='trails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trails_route', 'trails', ['route'], unique=False)
    # ### end Alembic commands ###
