"""empty message

Revision ID: 80349f751d69
Revises: 
Create Date: 2020-07-12 16:38:13.868432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80349f751d69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('route', geoalchemy2.types.Geography(geometry_type='MULTILINESTRING', from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trails')
    # ### end Alembic commands ###
