on: push
name: on push
jobs:
  gitHubActionForPylint:
    name: GitHub Action for pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@master
      with:
        args: pylint **/*.py
    - name: ESLint Action
      uses: hallee/eslint-action@1.0.3
